Repository bbman9900/Ducktion, pull requests merged in 2024-12, with the labels that each got.

#5 feat: 커뮤니티 개설 요청 페이지 (#2)
  fe/package-lock.json
  fe/package.json
  fe/src/pages/RequestAddCommunity.tsx
Labels: design

#8 DT-01-01 커뮤니티 개설 요청
  fe/eslint.config.js
  fe/package-lock.json
  fe/package.json
  fe/src/main.jsx
  fe/src/pages/RequestAddCommunity.jsx
Labels: design

#10 DT-FE-컴포넌트 생성
  fe/eslint.config.js
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/assets/assets.txt
  fe/src/assets/duck.png
  fe/src/assets/duck_selected.png
  fe/src/assets/test_image.png
  fe/src/components/BidHistoryCard.jsx
  fe/src/components/Button/RectangleButton.jsx
  fe/src/components/Button/RoundButton.jsx
  fe/src/components/CustomTextField.jsx
  fe/src/components/ItemCard/ItemCard.jsx
  fe/src/components/Labels/GodoSubTitleLabel.jsx
  fe/src/components/Labels/GodoTextLabel.jsx
  fe/src/components/Labels/GodoTitleLabel.jsx
  fe/src/components/Labels/IconPlusLabel.jsx
  fe/src/components/Labels/PreCaptionLabel.jsx
  fe/src/components/Labels/PreSubTitleLabel.jsx
  fe/src/components/Labels/PreTextLabel.jsx
  fe/src/components/Labels/PreTitleLabel.jsx
  fe/src/components/components.txt
  fe/src/main.jsx
  fe/src/pages/RequestAddCommunity.tsx
  fe/src/pages/pages.txt
  fe/src/styles/Fonts.css
  fe/src/styles/components/BidHistoryCard.css
  fe/src/styles/components/Buttons.css
  fe/src/styles/components/ItemCard.css
  fe/src/styles/components/Labels.css
  fe/src/styles/components/TextField.css
  fe/vite.config.js
Labels: design

#12 DT-H-01 헤더, DT-F-01 풋터
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/assets/comunity.png
  fe/src/assets/gitLogo.png
  fe/src/assets/login.png
  fe/src/assets/logout.png
  fe/src/assets/mypage.png
  fe/src/assets/notion.png
  fe/src/components/BidHistoryCard.jsx
  fe/src/components/Button/RectangleButton.jsx
  fe/src/components/Button/RoundButton.jsx
  fe/src/components/CustomTextField.jsx
  fe/src/components/Footer.jsx
  fe/src/components/Header.jsx
  fe/src/components/ItemCard/ItemCard.jsx
  fe/src/components/Labels/GodoSubTitleLabel.jsx
  fe/src/components/Labels/GodoTextLabel.jsx
  fe/src/components/Labels/GodoTitleLabel.jsx
  fe/src/components/Labels/IconPlusLabel.jsx
  fe/src/components/Labels/PreCaptionLabel.jsx
  fe/src/components/Labels/PreSubTitleLabel.jsx
  fe/src/components/Labels/PreTextLabel.jsx
  fe/src/components/Labels/PreTitleLabel.jsx
  fe/src/pages/RequestAddCommunity.jsx
  fe/src/routes/Routers.jsx
  fe/src/routes/routes.txt
  fe/src/styles/App.css
  fe/src/styles/components/HeaderFooter.css
Labels: design

#17 DT-01 커뮤니티 목록 보기
  fe/src/App.jsx
  fe/src/pages/ViewCommunityList.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/api.jsx
Labels: design

#19 DT-01-02 출품 상품 목록 보기
  fe/src/assets/search.png
  fe/src/components/Button/RoundButton.jsx
  fe/src/components/CustomTextField.jsx
  fe/src/components/Header.jsx
  fe/src/components/ItemCard/ItemCard.jsx
  fe/src/components/SearchTextField.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/communityService.js
  fe/src/services/itemsService.js
  fe/src/styles/components/TextField.css
  fe/src/styles/pages/ViewItemList.css
Labels: design

#14 DT-01-01 커뮤니티 개설요청 / DT-03-03-03 출품상품 삭제요청
  fe/src/components/PostForm.jsx
  fe/src/main.jsx
  fe/src/pages/RequestAddCommunity.jsx
  fe/src/pages/RequestDeleteItem.jsx
  fe/src/styles/PostForm.css
Labels: design

#27 DT-03-04 관심 상품 목록 보기
  fe/src/pages/ViewFavoriteItemList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/styles/pages/ViewMypage.css
Labels: design

#29 DT-03-03 출품 이력 보기
  fe/src/assets/nextMonth.png
  fe/src/assets/preMonth.png
  fe/src/components/Button/RoundButton.jsx
  fe/src/components/DateNavigator.jsx
  fe/src/pages/ViewBiddedHistoryList.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/itemsService.js
  fe/src/styles/components/Buttons.css
  fe/src/styles/components/DateNavigator.css
  fe/src/styles/pages/ViewBiddedHistory.css
  fe/src/styles/pages/ViewItemList.css
Labels: design

#28 DT-01-02-01 출품 상품 등록
  fe/src/assets/camera.png
  fe/src/assets/empty_star.png
  fe/src/assets/full_star.png
  fe/src/assets/half_star.png
  fe/src/components/Button/StarRating.jsx
  fe/src/components/Calendar.jsx
  fe/src/components/NumericInput.jsx
  fe/src/pages/RegistItem.jsx
  fe/src/pages/ViewCommunityList.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/api.js
  fe/src/services/communityService.js
  fe/src/services/itemsService.js
  fe/src/styles/components/StarRating.css
  fe/src/styles/pages/RegistItem.css
  fe/src/utils/ImageFileValidators.js
Labels: design

#33 DT-03-02 입찰 이력 보기
  fe/src/components/BiddingHistoryList.jsx
  fe/src/components/ItemCard/ItemCardRow.jsx
  fe/src/pages/ViewBiddedHistoryList.jsx
  fe/src/pages/ViewBiddingHistoryList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/itemsService.js
  fe/src/styles/components/BiddingHistoryList.css
  fe/src/styles/components/ItemCardRow.css
  fe/src/styles/pages/ViewBiddingHistory.css
Labels: design

#38 DT-03 마이페이지 중간 병합
  fe/package-lock.json
  fe/package.json
  fe/src/assets/heldBid.png
  fe/src/assets/rate.png
  fe/src/assets/usableBiid.png
  fe/src/components/Header.jsx
  fe/src/components/Historybox.jsx
  fe/src/components/Labels/IconPlusLabel.jsx
  fe/src/components/Labels/IconPlusLabelColumn.jsx
  fe/src/components/ProfileImage.jsx
  fe/src/pages/ViewCommunityList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/services/itemsService.js
  fe/src/styles/components/HistoryBox.css
  fe/src/styles/components/Labels.css
  fe/src/styles/pages/ViewMypage.css
Labels: design

#42 DT-03 마이페이지
  fe/src/components/Historybox.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/services/itemsService.js
  fe/src/services/uesrService.js
  fe/src/styles/pages/ViewMypage.css
Labels: design

#46 remove: api.jsx, utils.txt 삭제
  fe/src/services/api.jsx
  fe/src/utils/utils.txt
Labels: remove

#47 DT-03-05 비드 이력 보기
  fe/src/components/BidPointHistoryCard.jsx
  fe/src/components/Labels/PreCaptionLabel.jsx
  fe/src/pages/ViewBidPointHistoryList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/bidService.js
  fe/src/styles/pages/ViewBidPointHistoryList.css
Labels: design

#49 DT-03-01 내 정보 보기
  fe/src/components/HorizontalRule.jsx
  fe/src/pages/ViewMyInfo.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/uesrService.js
  fe/src/styles/components/HorizontalRule.css
  fe/src/styles/pages/ViewMyInfo.css
Labels: design

#50 DT-03-06 요청/ 신고/ 검수 목록 페이지 구현.
  fe/package-lock.json
  fe/package.json
  fe/src/components/Labels/HorizontalRule.jsx
  fe/src/pages/ViewAdminPage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/adminService.js
  fe/src/styles/components/Labels.css
  fe/src/styles/components/ViewAdminPage.css
Labels: design

#51 design: 임포트문 컴포넌트들 경로 변경 (#37)
  fe/src/pages/ViewAdminPage.jsx
Labels: design

#52 DT-M 모달
  fe/package-lock.json
  fe/package.json
  fe/src/assets/give_up.png
  fe/src/assets/kakaoLoginButton.png
  fe/src/assets/left_arrow.png
  fe/src/assets/minus.png
  fe/src/assets/plus.png
  fe/src/assets/report.png
  fe/src/assets/right_arrow.png
  fe/src/components/Header.jsx
  fe/src/components/Modal/BidInputTextField.jsx
  fe/src/components/Modal/ChargeBidPointModalContent.jsx
  fe/src/components/Modal/CustomModal.jsx
  fe/src/components/Modal/DropdownInput.jsx
  fe/src/components/Modal/InputInvoiceModalContent.jsx
  fe/src/components/Modal/LoginModalContent.jsx
  fe/src/components/Modal/OutputInvoiceModalContent.jsx
  fe/src/components/Modal/SubmitBidModalContent.jsx
  fe/src/components/Modal/UserRatingModalContent.jsx
  fe/src/components/Modal/WithdrwalBidPointModalContent.jsx
  fe/src/components/PriceSummary.jsx
  fe/src/hooks/hooks.txt
  fe/src/hooks/useModal.jsx
  fe/src/pages/EditItem.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/RegistItem.jsx
  fe/src/pages/ViewBidPointHistoryList.jsx
  fe/src/pages/ViewBiddedHistoryList.jsx
  fe/src/pages/ViewBiddingHistoryList.jsx
  fe/src/pages/ViewItem.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/pages/ViewMyInfo.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/pages/ViewSearchResult.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/bidService.js
  fe/src/services/invoiceService.js
  fe/src/services/itemService.js
  fe/src/services/uesrService.js
  fe/src/styles/components/PriceSummary.css
  fe/src/styles/components/modal/BidInputTextField.css
  fe/src/styles/components/modal/BidPointModalContent.css
  fe/src/styles/components/modal/CustomModal.css
  fe/src/styles/components/modal/DropdownInput.css
  fe/src/styles/components/modal/LoginModalContent.css
  fe/src/styles/components/modal/RatingInputModal.css
  fe/src/styles/pages/ViewItem.css
  fe/src/utils/numericInputValidate.js
Labels: design

#53 DT-01-02-02 출품 상품 보기
  fe/src/components/PriceSummary.jsx
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
  fe/src/styles/pages/ViewItem.css
Labels: design, fix

#57 fix: itemService tatalView -> totalView 오타 수정
  fe/src/services/itemService.js
Labels: fix

#56 DT-03-06-01 커뮤니티개설요청 상세
  fe/src/pages/ViewAdminPage.jsx
  fe/src/pages/ViewRequestAddCommunity.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/adminService.js
Labels: design

#113 Docker MySQL 9.1.0 버전 DB 연결, Item 테이블의 condition 속성 이름 변경
  .gitignore
  be/src/main/java/shop/duction/be/item/entity/Item.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
Labels: feat, fix

#115 spring-boot-devtools 의존성 추가, .gitignore 에 .env 파일 제외 추가
  .gitignore
  be/build.gradle
Labels: feat, fix

#119 Item 도메인 엔티티 수정
  be/local.env
  be/src/main/java/shop/duction/be/item/entity/FavoriteItem.java
  be/src/main/java/shop/duction/be/item/entity/Item.java
  be/src/main/java/shop/duction/be/item/entity/ItemImage.java
  be/src/main/java/shop/duction/be/item/entity/RareRating.java
  be/src/main/java/shop/duction/be/item/entity/UserItemKey.java
  be/src/main/java/shop/duction/be/item/entity/UserLog.java
  be/src/main/java/shop/duction/be/item/enums/BiddingStatus.java
  be/src/main/java/shop/duction/be/item/enums/ProductCondition.java
  be/src/main/java/shop/duction/be/item/enums/RareTier.java
Labels: fix

#121 User 도메인 엔티티 수정
  be/src/main/java/shop/duction/be/user/entity/User.java
  be/src/main/java/shop/duction/be/user/enums/IsActive.java
  be/src/main/java/shop/duction/be/user/enums/Role.java
Labels: fix

#123 Admin 도메인 엔티티 수정
  be/src/main/java/shop/duction/be/admin/entity/ItemDeleteRequest.java
Labels: fix

#125 Community 도메인 엔티티 수정
  be/src/main/java/shop/duction/be/community/entity/Community.java
  be/src/main/java/shop/duction/be/community/entity/FavoriteCommunity.java
  be/src/main/java/shop/duction/be/community/entity/FavoriteCommunityId.java
Labels: fix

#128 상품 수정하기, 수정할 상품 정보 보기 API 구현 및 기타 작업
  be/build.gradle
  be/src/main/java/shop/duction/be/config/ModelMapperConfig.java
  be/src/main/java/shop/duction/be/config/config.txt
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/item/dto/ItemEditRequestDTO.java
  be/src/main/java/shop/duction/be/domain/item/dto/ViewItemEditResponseDTO.java
  be/src/main/java/shop/duction/be/domain/item/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/item/entity/Item.java
  be/src/main/java/shop/duction/be/domain/item/entity/RareRating.java
  be/src/main/java/shop/duction/be/domain/item/repository/ItemRepository.java
  be/src/main/java/shop/duction/be/domain/item/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/domain/item/service/service.txt
  be/src/main/java/shop/duction/be/exception/GlobalExceptionHandler.java
  be/src/main/java/shop/duction/be/exception/ItemNotFoundException.java
  be/src/main/java/shop/duction/be/exception/exception.txt
  be/src/main/java/shop/duction/be/utils/HttpStatusConstants.java
  be/src/main/java/shop/duction/be/utils/utils.txt
  be/src/main/resources/application.yml
Labels: feat

#129 Feature/be-062
  be/build.gradle
  be/src/main/java/shop/duction/be/domain/bidpoint/controller/BidPointController.java
  be/src/main/java/shop/duction/be/domain/bidpoint/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/bidpoint/repository/BidHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidpoint/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/bidpoint/service/BidPointService.java
  be/src/main/java/shop/duction/be/domain/bidpoint/service/service.txt
  be/src/main/java/shop/duction/be/domain/community/controller/CommunityController.java
  be/src/main/java/shop/duction/be/domain/community/controller/FavoriteCommunityController.java
  be/src/main/java/shop/duction/be/domain/community/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/community/dto/PopularCommunitiesResponseDto.java
  be/src/main/java/shop/duction/be/domain/community/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/community/entity/FavoriteCommunityId.java
  be/src/main/java/shop/duction/be/domain/community/repository/CommunityRepository.java
  be/src/main/java/shop/duction/be/domain/community/repository/FavoriteCommunityRepository.java
  be/src/main/java/shop/duction/be/domain/community/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/community/service/CommunityService.java
  be/src/main/java/shop/duction/be/domain/community/service/FavoriteCommunityService.java
  be/src/main/java/shop/duction/be/domain/community/service/service.txt
  be/src/main/java/shop/duction/be/domain/item/controller/FavoriteItemController.java
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/dto/ItemCardResponseDto.java
  be/src/main/java/shop/duction/be/domain/item/enums/AuctionStatus.java
  be/src/main/java/shop/duction/be/domain/item/repository/FavoriteItemRepository.java
  be/src/main/java/shop/duction/be/domain/item/repository/ItemRepository.java
  be/src/main/java/shop/duction/be/domain/item/service/FavoriteItemService.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/domain/user/repository/UserRepository.java
  be/src/main/java/shop/duction/be/domain/user/repository/repository.txt
  be/src/main/resources/application.yml
  fe/package-lock.json
  fe/package.json
  fe/src/components/CommunityList.jsx
  fe/src/components/Header.jsx
  fe/src/components/ItemCard/ItemCard.jsx
  fe/src/components/ItemCard/ItemCardList.jsx
  fe/src/components/Labels/IconPlusLabel.jsx
  fe/src/components/Labels/PreTextLabel.jsx
  fe/src/components/Modal/ChargeBidPointModalContent.jsx
  fe/src/components/Modal/SubmitBidModalContent.jsx
  fe/src/components/Modal/WithdrwalBidPointModalContent.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/ViewBidPointHistoryList.jsx
  fe/src/services/api.js
  fe/src/services/bidPointService.js
  fe/src/services/communityService.js
  fe/src/services/itemService.js
  fe/src/utils/CheckLogin.js
Labels: feat

#131 BidHistory, BiddedHistory엔티티 수정
  be/src/main/java/shop/duction/be/domain/bidding/entity/BiddedHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/entity/BiddingHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/entity/ExhibitHistory.java
  be/src/main/java/shop/duction/be/domain/bidpoint/entity/BidHistory.java
Labels: fix

#132 Feature/be 102
  be/src/main/java/shop/duction/be/domain/bidding/entity/BiddedHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/entity/ExhibitHistory.java
  be/src/main/java/shop/duction/be/domain/bidpoint/controller/BidPointController.java
  be/src/main/java/shop/duction/be/domain/bidpoint/dto/BidPointHistoriesRequestDto.java
  be/src/main/java/shop/duction/be/domain/bidpoint/dto/BidPointHistoriesResponseDto.java
  be/src/main/java/shop/duction/be/domain/bidpoint/dto/UserBidPointResponse.java
  be/src/main/java/shop/duction/be/domain/bidpoint/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/bidpoint/entity/BidHistory.java
  be/src/main/java/shop/duction/be/domain/bidpoint/enums/BidPointHistoriesSortType.java
  be/src/main/java/shop/duction/be/domain/bidpoint/enums/BidPointType.java
  be/src/main/java/shop/duction/be/domain/bidpoint/enums/BidpointType.java
  be/src/main/java/shop/duction/be/domain/bidpoint/repository/BidHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidpoint/service/BidPointService.java
  be/src/main/java/shop/duction/be/domain/user/repository/UserRepository.java
  be/src/main/java/shop/duction/be/utils/DateTimeFormatterUtil.java
  fe/src/components/Modal/WithdrwalBidPointModalContent.jsx
  fe/src/pages/ViewBidPointHistoryList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/bidPointService.js
Labels: feat, design

#133 출품 상품 상세 보기 API 구현, BiddedHistory 엔티티, BidHistory 연관 관계 수정
  be/src/main/java/shop/duction/be/domain/bidpoint/controller/BidPointController.java
  be/src/main/java/shop/duction/be/domain/bidpoint/entity/BidHistory.java
  be/src/main/java/shop/duction/be/domain/community/controller/CommunityController.java
  be/src/main/java/shop/duction/be/domain/community/controller/FavoriteCommunityController.java
  be/src/main/java/shop/duction/be/domain/item/controller/FavoriteItemController.java
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/dto/ViewItemDetailsDTO.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/utils/ItemConditionConverter.java
  be/src/main/java/shop/duction/be/utils/RareTierConverter.java
  fe/src/components/PriceSummary.jsx
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat, design, fix

#134 출품상품 레어 점수 평가 API 구현
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/dto/ItemRareScoreRequestDTO.java
  be/src/main/java/shop/duction/be/domain/item/dto/ViewItemDetailsResponseDTO.java
  be/src/main/java/shop/duction/be/domain/item/repository/RareRatingRepository.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/utils/RareTierCheck.java
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat, fix

#135 신고하기 API 구현
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat, fix

#136 Feature/be 068
  be/src/main/java/shop/duction/be/domain/bidding/entity/ExhibitHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/enums/BiddingStatus.java
  be/src/main/java/shop/duction/be/domain/bidding/enums/ExhibitStatus.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/BiddingHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/ExhibitHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/bidpoint/repository/BidHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidpoint/service/BidPointService.java
  be/src/main/java/shop/duction/be/domain/item/controller/FavoriteItemController.java
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/dto/AuctionItemsRequestDto.java
  be/src/main/java/shop/duction/be/domain/item/dto/BiddingHistoriesResponseDto.java
  be/src/main/java/shop/duction/be/domain/item/dto/HistoriesCountResponseDto.java
  be/src/main/java/shop/duction/be/domain/item/dto/HistoriesRequestDto.java
  be/src/main/java/shop/duction/be/domain/item/dto/ItemCardResponseDto.java
  be/src/main/java/shop/duction/be/domain/item/repository/FavoriteItemRepository.java
  be/src/main/java/shop/duction/be/domain/item/repository/ItemRepository.java
  be/src/main/java/shop/duction/be/domain/item/service/FavoriteItemService.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/utils/DateTimeFormatterUtil.java
  be/src/main/java/shop/duction/be/utils/DateTimeUtils.java
  fe/src/pages/ViewBiddingHistoryList.jsx
  fe/src/pages/ViewExhibitHistoryList.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/pages/ViewMypage.jsx
  fe/src/routes/Routers.jsx
  fe/src/services/communityService.js
  fe/src/services/itemService.js
Labels: feat, design

#137 Feature/be 088
  be/src/main/java/shop/duction/be/domain/item/dto/BiddingHistoriesResponseDto.java
  be/src/main/java/shop/duction/be/domain/user/controller/UserController.java
  be/src/main/java/shop/duction/be/domain/user/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/user/dto/ExhibitorRatingRequestDto.java
  be/src/main/java/shop/duction/be/domain/user/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/user/repository/ExhibitorRatingRepository.java
  be/src/main/java/shop/duction/be/domain/user/service/UserService.java
  be/src/main/java/shop/duction/be/domain/user/service/service.txt
  be/src/main/java/shop/duction/be/exception/GlobalExceptionHandler.java
  fe/src/components/Modal/UserRatingModalContent.jsx
  fe/src/pages/ViewBiddingHistoryList.jsx
  fe/src/services/uesrService.js
Labels: feat, design

#138 Feature/be 105
  be/src/main/java/shop/duction/be/domain/ship/controller/ShipController.java
  be/src/main/java/shop/duction/be/domain/ship/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/ship/dto/ExhibitorShipInfoRequestDto.java
  be/src/main/java/shop/duction/be/domain/ship/dto/ShipInfoResponseDto.java
  be/src/main/java/shop/duction/be/domain/ship/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/ship/enums/DeliveryId.java
  be/src/main/java/shop/duction/be/domain/ship/repository/BidderShipRepository.java
  be/src/main/java/shop/duction/be/domain/ship/repository/ExhibitorShipRepository.java
  be/src/main/java/shop/duction/be/domain/ship/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/ship/service/ShipService.java
  be/src/main/java/shop/duction/be/domain/ship/service/service.txt
  be/src/main/java/shop/duction/be/domain/user/service/UserService.java
  be/src/main/java/shop/duction/be/utils/DateTimeUtils.java
  fe/src/components/Modal/InputInvoiceModalContent.jsx
  fe/src/components/Modal/OutputInvoiceModalContent.jsx
  fe/src/pages/ViewBiddingHistoryList.jsx
  fe/src/pages/ViewExhibitHistoryList.jsx
  fe/src/services/invoiceService.js
  fe/src/services/shipService.js
Labels: feat, design

#140 Feature/be 089
  be/src/main/java/shop/duction/be/domain/admin/controller/AdminController.java
  be/src/main/java/shop/duction/be/domain/admin/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/admin/dto/CreateCommunityResponseDto.java
  be/src/main/java/shop/duction/be/domain/admin/dto/DeleteItemResponseDto.java
  be/src/main/java/shop/duction/be/domain/admin/dto/ReportInfoResponseDto.java
  be/src/main/java/shop/duction/be/domain/admin/dto/ValidateItemInfoResponseDto.java
  be/src/main/java/shop/duction/be/domain/admin/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/admin/entity/ItemDeleteRequest.java
  be/src/main/java/shop/duction/be/domain/admin/repository/CommunityCreateRequestRepository.java
  be/src/main/java/shop/duction/be/domain/admin/repository/ItemDeleteRequestRepository.java
  be/src/main/java/shop/duction/be/domain/admin/repository/repository.txt
  be/src/main/java/shop/duction/be/domain/admin/service/AdminService.java
  be/src/main/java/shop/duction/be/domain/admin/service/service.txt
  be/src/main/java/shop/duction/be/domain/item/repository/ItemRepository.java
  fe/src/components/AdminTable.jsx
  fe/src/pages/ViewAdminDetailPage.jsx
  fe/src/pages/ViewAdminPage.jsx
  fe/src/services/adminService.js
Labels: feat

#141 입찰하기 API 구현, BidHistory 연관 관계 수정
  be/src/main/java/shop/duction/be/domain/bidding/controller/BiddingController.java
  be/src/main/java/shop/duction/be/domain/bidding/controller/controller.txt
  be/src/main/java/shop/duction/be/domain/bidding/dto/BidRequestDTO.java
  be/src/main/java/shop/duction/be/domain/bidding/dto/dto.txt
  be/src/main/java/shop/duction/be/domain/bidding/entity/BiddingHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/service/BiddingService.java
  be/src/main/java/shop/duction/be/domain/bidding/service/service.txt
  be/src/main/java/shop/duction/be/domain/bidpoint/entity/BidHistory.java
  be/src/main/java/shop/duction/be/domain/user/entity/User.java
  fe/src/components/Modal/SubmitBidModalContent.jsx
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat, fix

#143 입찰 포기 API 구현
  be/src/main/java/shop/duction/be/domain/bidding/controller/BiddingController.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/BiddingHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidding/service/BiddingService.java
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat

#144 즉시 낙찰 API 구현, SubmitBidModalContent.jsx 변수명 수정
  be/src/main/java/shop/duction/be/domain/bidding/controller/BiddingController.java
  be/src/main/java/shop/duction/be/domain/bidding/entity/BiddedHistory.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/BiddedHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidding/service/BiddingService.java
  fe/src/components/Modal/SubmitBidModalContent.jsx
  fe/src/pages/ViewItem.jsx
  fe/src/services/itemService.js
Labels: feat, fix

#147 출품 이력 엔티티 복합키 해제
  be/src/main/java/shop/duction/be/domain/bidding/entity/ExhibitHistory.java
Labels: fix

#148 Feature/be 093
  be/src/main/java/shop/duction/be/domain/admin/controller/AdminController.java
  be/src/main/java/shop/duction/be/domain/admin/service/AdminService.java
  be/src/main/java/shop/duction/be/domain/bidding/repository/BiddingHistoryRepository.java
  be/src/main/java/shop/duction/be/domain/bidpoint/entity/BidHistory.java
  be/src/main/java/shop/duction/be/domain/item/entity/Item.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/domain/ship/controller/ShipController.java
  be/src/main/java/shop/duction/be/domain/ship/dto/ShipRequestDto.java
  be/src/main/java/shop/duction/be/domain/ship/service/ShipService.java
  be/src/main/java/shop/duction/be/utils/email/EmailMessageInfo.java
  be/src/main/java/shop/duction/be/utils/email/SendEamilMessage.java
  fe/src/components/AdminTable.jsx
  fe/src/components/Modal/InputInvoiceModalContent.jsx
  fe/src/pages/ViewExhibitHistoryList.jsx
  fe/src/services/adminService.js
Labels: feat

#149 Feature/be 087
  be/src/main/java/shop/duction/be/domain/user/controller/UserController.java
  be/src/main/java/shop/duction/be/domain/user/dto/EditUserInfoRequestDto.java
  be/src/main/java/shop/duction/be/domain/user/dto/MyInfoResponseDto.java
  be/src/main/java/shop/duction/be/domain/user/service/UserService.java
  fe/src/pages/ViewMyInfo.jsx
  fe/src/services/uesrService.js
Labels: feat

#150 상품 등록하기 API 구현, AWS S3 의존성 추가, 전역 CORS 추가
  be/build.gradle
  be/src/main/java/shop/duction/be/config/WebConfig.java
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/dto/EditItemRequestDTO.java
  be/src/main/java/shop/duction/be/domain/item/dto/RegistItemRequestDTO.java
  be/src/main/java/shop/duction/be/domain/item/dto/ViewItemEditResponseDTO.java
  be/src/main/java/shop/duction/be/domain/item/enums/ItemCondition.java
  be/src/main/java/shop/duction/be/domain/item/repository/ItemImageRepository.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/utils/RareTierCheckUtils.java
  be/src/main/java/shop/duction/be/utils/aws/AwsConfig.java
  be/src/main/java/shop/duction/be/utils/aws/PresignedURLRequestDTO.java
  be/src/main/java/shop/duction/be/utils/aws/PresignedURLResponseDTO.java
  be/src/main/java/shop/duction/be/utils/aws/S3Controller.java
  be/src/main/resources/application.yml
  fe/src/pages/RegistItem.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/services/itemService.js
  fe/src/utils/S3Uploader.js
Labels: feat

#151 Feature/be 065
  be/src/main/java/shop/duction/be/domain/admin/controller/AdminController.java
  be/src/main/java/shop/duction/be/domain/admin/dto/CreateCommunityRequestDto.java
  be/src/main/java/shop/duction/be/domain/admin/dto/DeleteItemRequestDto.java
  be/src/main/java/shop/duction/be/domain/admin/entity/ItemDeleteRequest.java
  be/src/main/java/shop/duction/be/domain/admin/service/AdminService.java
  fe/src/pages/RequestAddCommunity.jsx
  fe/src/pages/RequestDeleteItem.jsx
  fe/src/services/adminService.js
Labels: feat

#152 프로필 사진 변경하기 API 구현, S3Uploader.js 수정
  be/src/main/java/shop/duction/be/domain/item/controller/ItemController.java
  be/src/main/java/shop/duction/be/domain/item/service/ItemService.java
  be/src/main/java/shop/duction/be/domain/user/controller/UserController.java
  be/src/main/java/shop/duction/be/domain/user/dto/ProfileImageEditRequestDTO.java
  be/src/main/java/shop/duction/be/domain/user/service/UserService.java
  fe/src/pages/ViewMyInfo.jsx
  fe/src/services/uesrService.js
  fe/src/utils/S3Uploader.js
Labels: feat, fix

#153 프로필 사진 삭제하기 API 구현
  be/src/main/java/shop/duction/be/domain/user/controller/UserController.java
  be/src/main/java/shop/duction/be/domain/user/service/UserService.java
  fe/src/pages/ViewMyInfo.jsx
  fe/src/services/uesrService.js
Labels: feat

#155 카카오 로그인 구현
  be/build.gradle
  be/src/main/java/shop/duction/be/domain/user/entity/User.java
  be/src/main/java/shop/duction/be/domain/user/repository/UserRepository.java
  be/src/main/java/shop/duction/be/security/AuthController.java
  be/src/main/java/shop/duction/be/security/CustomOAuth2User.java
  be/src/main/java/shop/duction/be/security/CustomOAuth2UserService.java
  be/src/main/java/shop/duction/be/security/JwtAuthenticationFilter.java
  be/src/main/java/shop/duction/be/security/JwtProvider.java
  be/src/main/java/shop/duction/be/security/KakaoOAuthService.java
  be/src/main/java/shop/duction/be/security/KakaoUser.java
  be/src/main/java/shop/duction/be/security/SecurityConfig.java
  be/src/main/java/shop/duction/be/security/security.txt
  be/src/main/resources/application.yml
  fe/src/components/Modal/LoginModalContent.jsx
  fe/src/services/uesrService.js
Labels: feat

#157 Feature/be 061
  be/src/main/java/shop/duction/be/domain/community/controller/CommunityController.java
  be/src/main/java/shop/duction/be/domain/community/dto/CommunityListResponseDTO.java
  be/src/main/java/shop/duction/be/domain/community/repository/CommunityRepository.java
  be/src/main/java/shop/duction/be/domain/community/repository/FavoriteCommunityRepository.java
  be/src/main/java/shop/duction/be/domain/community/service/CommunityService.java
  be/src/main/java/shop/duction/be/domain/community/service/FavoriteCommunityService.java
  fe/src/components/CommunityList/AllCommunityList.jsx
  fe/src/components/CommunityList/CharCommunityList.jsx
  fe/src/components/CommunityList/CommunityList.jsx
  fe/src/components/Labels/GodoTitleLabel.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/ViewCommunityList.jsx
  fe/src/pages/ViewSearchResult.jsx
  fe/src/services/communityService.js
  fe/src/styles/pages/ViewCommunityList.css
Labels: feat, design

#159 design: 커뮤니티 개설 요청 버튼 추가 및 출품 상품 목록에서 커뮤니티 이름 표시되도록 수정 (#3)
  fe/src/components/CommunityList/CharCommunityList.jsx
  fe/src/components/CommunityList/CommunityList.jsx
  fe/src/pages/ViewCommunityList.jsx
  fe/src/pages/ViewItemList.jsx
  fe/src/styles/pages/ViewCommunityList.css
Labels: design
